### ISSUE TITLE
Make @HensonNavigable work even if @InjectExtra is present

### ISSUE THREAD

**Issue by bryant1410** [f2prateek/dart#104]
What about the fact of making `@HensonNavigable` to work, even if the `Activity` contains `@InjectExtra` annotated fields? In a similar way to `@FragmentWithArgs` annotation from [fragmentargs](https://github.com/sockeqwe/fragmentargs), this can allow to just annotate all activities, and then if extras are changed during the development cycle (even when all are removed) it still works.

**Comment by stephanenicolas** [comment]
The problem is that Henson navigable means to create a DSL without
attributes. Inject extra means to create a DSL with attributes. Moreover,
now Henson navigable uses a model class from which to use inject extras. If
we also have inject extra in the activity, we wouldn't know clearly how to
crate the DSL, and it would not be possible to bind all fields with
Dart.inject()..

Henson navigable is really a trick to trigger the annotation process
without inject extra annotations. IMHO, it should just remain exactly that,
the semantics are much more clear this way.

Le ven. 4 mars 2016 05:40, Santiago Castro <notifications@github.com> a
écrit :
