### ISSUE TITLE
The changes do not reflect immediately in Henson intent builder

### ISSUE THREAD

**Issue by jaychang0917** [f2prateek/dart#119]
Each time I add new extras in one Activity, I need to remake the project to see the changes. I have already used android apt. Is this a bug? 

Thanks!

**Comment by stephanenicolas** [comment]
Henson uses annotation processing, it entirely relies on the compile part
of the Android build process. Nothing can be done beyond that.
Incremental compilation in Android studio should actually work immediately
though.

Maybe a few questions :
1) which version of Andoid Studio do you use ?
2) does a simple build of the module solve the issue ? Or do you need to
rebuild all the project ? Do you need to clean ?
3) are the generated classes created in the build folder and just "not
visible immediately" in Android Studio ? Or the classes are not created
before you trigger a complete rebuild ?

Even with these answers, I guess the only thing we can do about it is to
write a more precise bug report to Google about Android Studio's ability to
deal with code generated by annotation processors but this is most likely
to be completely out of the scope of dart & henson.

2016-06-09 8:08 GMT-07:00 Jay <notifications@github.com>:

**Comment by jaychang0917** [comment]
1) Android Studio 2.2 Preview 3
2) A simple `Make module app` solve the issue.
3) After done a `Make module app` action, the latest code was generated in build folder.

**Comment by stephanenicolas** [comment]
@jaychang0917 everything seems normal to me: as Henson is based on annotation processing and this is part of compilation, yeah you need to compile your project when you make a change so that henson reflects the change.. 

Can we close the issue or your wanna add anything else ?

**Comment by jaychang0917** [comment]
@stephanenicolas I got it, you can close it.

**Comment by stephanenicolas** [comment]
let's go a little bit further on this:

when you type a bad statement in Android Studio (AS), it gets highlighted immediately. This is incremental compilation and it uses javac. 

So, as devs, we could hope that the code generated by the annotation processor would also be updated as javac is called.

BUT, the incremental compilation is not a full compilation. Compilation can be divided into 2 phases: 
1) from java source, javac creates an Abstract Syntax Tree (AST)
2) from the AST javac produces byte code. 

The annotation processors are also triggered during phase 2 as their need the AST as an input to work.

But incremental, or on-the-fly compilation, in IDEs only triggers the first part. This is fast, it is only in-memory and is enough to higligh errors fast as you type. But it doesn't get into phase 2 of compilation. So you actually need to build / compile your code so that Henson generates code.
