### ISSUE TITLE
Generate Henson code even if no extra needed?

### ISSUE THREAD

**Issue by bagage** [f2prateek/dart#197]
I'm trying to use the `Henson.with(this).gotoXXXActivity()` everywhere in my project to keep consistent code practice and avoid mixing up two different invocations style which would confuse others developers (incl. my future me).
But it seems to me that until I add some field `@InjectExtra`, Henson code won't be generated for the activity and thus compiler yields `cannot find symbol method gotoXXXActivity()`. 

I'd like to avoid having a dummy field for that, but is there another solution?

Thanks!

**Comment by stephanenicolas** [comment]
It's not very clear what the issue is. You should actually do it the other way around: make it so that Henson code is generated, and rely on auto completion to find your methods.

If an activity doesn't need any @InjectExtra annotation, use @HensonNavigable. This will make the activity visible to Henson as well.

**Comment by bagage** [comment]
Thanks @stephanenicolas, I was indeed looking for that -- I somewhat missed it from the doc!
